name: Build and deploy Node.js project to Azure Function App - jobs-prachi

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  NODE_VERSION: '20.x'                  # Node version
  FUNCTIONAPP_PATH: 'function-app'      # <-- your Functions folder

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install & build function app
        shell: pwsh
        run: |
          pushd ${{ env.FUNCTIONAPP_PATH }}
          npm install
          npm run build --if-present
          npm run test  --if-present
          popd

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: function-app
          path: ${{ env.FUNCTIONAPP_PATH }}

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: function-app
          path: ${{ env.FUNCTIONAPP_PATH }}

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id:   ${{ secrets.AZUREAPPSERVICE_CLIENTID_… }}
          tenant-id:   ${{ secrets.AZUREAPPSERVICE_TENANTID_… }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_… }}

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: 'jobs-prachi'
          slot-name: 'Production'
          package: '${{ env.FUNCTIONAPP_PATH }}'
